export const GET_FILTERED_VIDEOS = 'GET_FILTERED_VIDEOS'
export const GET_BEGINNER_VIDEOS = 'GET_BEGINNER_VIDEOS'
export const GET_INTERMEDIATE_VIDEOS = 'GET_INTERMEDIATE_VIDEOS'
export const GET_ADVANCE_VIDEOS = 'GET_ADVANCE_VIDEOS'
