export const GET_ALPHA_LIST = 'GET_ALPHA_LIST'
export const GET_ALPHA_TAGS = 'GET_ALPHA_TAGS'
export const GET_LATEST_ALPHA_LIST = 'GET_LATEST_ALPHA_LIST'
export const SET_ALPHA_ITEM_BOOK_MARK = 'SET_ALPHA_ITEM_BOOK_MARK'