export const GET_COIN_RATING_LIST = 'GET_COIN_RATING_LIST'
export const GET_COIN_RATING_TYPE_LIST = 'GET_COIN_RATING_TYPE_LIST'
export const GET_COIN_BY_ID = 'GET_COIN_BY_ID'
export const GET_COIN_NEWS = 'GET_COIN_NEWS'
