export const ADD_TO_FAVOURTIES = 'ADD_TO_FAVOURTIES'
export const GET_FAVOURITES_LIST = 'GET_FAVOURITES_LIST'
export const REMOVE_FROM_FAVOURITES = 'REMOVE_FROM_FAVOURITES'
export const REMOVE_BOOKMARK_FROM_FAVOURITES = 'REMOVE_BOOKMARK_FROM_FAVOURITES'
